# docker-compose.yml
version: "3.8"
services:
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./src/bartender:/usr/local/apache2/htdocs/bartender
  php:
    container_name: php
    build: ./docker/php
    links:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./src/bartender:/usr/local/apache2/htdocs/bartender
    working_dir: /usr/local/apache2/htdocs/bartender
  composer:
    container_name: composer
    image: composer/composer
    volumes:
      - ./src/bartender:/usr/local/apache2/htdocs/bartender
    working_dir: /usr/local/apache2/htdocs/bartender
    command: install
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bartender
      MYSQL_USER: bartender
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80